### ISSUE TITLE
when try to convert pdf to jpeg i got this err "spawn pdftocairo ENOENT"

### ISSUE THREAD

**Issue by foramsojitra** [ksami/pdftoimage#3]
spawn pdftocairo ENOENT

while try to convert pdf

**Comment by RiggedToBlow** [comment]
will there be updates on this?

**Comment by joshReder82** [comment]
this error happens when some directory you specify does not exist or is not accessible, try this example
`const path = require('path');
var pdftoimage = require('pdftoimage');
var file = path.join(__dirname, '/FAC/ANEXO3.pdf');
 
// Returns a Promise
pdftoimage(file, {
  format: 'tiff',  // png, jpeg, tiff or svg, defaults to png
  prefix: 'img',  // prefix for each image except svg, defaults to input filename
  outdir: 'out'   // path to output directory, defaults to current directory
})
.then(function(){
  console.log('Conversion done');
})
.catch(function(err){
  console.log(err);
});`

**Comment by HvJosh** [comment]
you should install Poppler before using this library.
https://poppler.freedesktop.org/
sudo apt update
sudo apt install poppler-utils
